@host = http://localhost:5267

### ==========================================
### 1. PRODUTOS (ProdutosController)
### ==========================================

### Listar todos os produtos do estoque
GET {{host}}/api/produtos
Accept: application/json

###

### Cadastrar um novo produto no estoque
POST {{host}}/api/produtos
Content-Type: application/json

{
  "id": "POCO_X7",
  "nome": "Celular POCO X7",
  "price": 1800.00
}

###

### Atualizar os dados de um produto existente
PUT {{host}}/api/produtos/POCO_X6
Content-Type: application/json

{
  "id": "POCO_X6",
  "nome": "Celular POCO X6 Pro",
  "price": 1850.00
}

###

### Deletar um produto do estoque pelo ID
DELETE {{host}}/api/produtos/POCO_X7

###


### ==========================================
### 2. ITENS DO CARRINHO (ItemController)
### ==========================================

### Criar um item para ser usado no fluxo
# Nota: Repare que agora usamos o ID correto do produto "POCO_X6"
POST {{host}}/api/item
Content-Type: application/json

{
  "Id": "item_087771",
  "IdProduto": "POCO_X7",
  "Quantidade": 7
}

###


### ==========================================
### 3. PEDIDO COMPLETO (PedidoController)
### ==========================================

### Obter todos os itens que estão dentro do pedido
GET {{host}}/api/pedido
Accept: application/json

###

### Adicionar um item ao pedido (Fechar o Pedido)
# Nota: Passamos apenas o ID do pedido para disparar o fechamento do carrinho
POST {{host}}/api/pedido
Content-Type: application/json

{
  "id": "pedido_final_0817722",
  "cliente": "Mariana Souza"
}

###

### Remover o item do pedido passando o idProduto na URL
DELETE {{host}}/api/pedido/POCO_X7